//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketStack_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historical_Data
    {
        public System.Guid H_Data_ID { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Close { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Adj_High { get; set; }
        public Nullable<double> Adj_Low { get; set; }
        public Nullable<double> Adj_Close { get; set; }
        public Nullable<double> Adj_Open { get; set; }
        public Nullable<double> Adj_Volume { get; set; }
        public Nullable<double> Split_Factor { get; set; }
        public string Symbol { get; set; }
        public string Exchange { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> H_Id { get; set; }
    
        public virtual Historical Historical { get; set; }
    }
}
