//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketStack_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntraDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IntraDay()
        {
            this.IntraDay_Data = new HashSet<IntraDay_Data>();
        }
    
        public System.Guid IDay_Id { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<int> Offset { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Total { get; set; }
        public System.DateTime DateOfEntry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntraDay_Data> IntraDay_Data { get; set; }
    }
}
