//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketStack_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntraDay_Data
    {
        public System.Guid IDay_Data_ID { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Last { get; set; }
        public Nullable<double> Close { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Symbol { get; set; }
        public string Exchange { get; set; }
        public Nullable<System.Guid> IDay_Id { get; set; }
    
        public virtual IntraDay IntraDay { get; set; }
    }
}
